name: Publish lambda

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      releases: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          enable-uv-cache: false # No caching to ensure correct dependencies for publishing
          sync-uv: false

      - name: Sync uv
        run: uv export --frozen --all-extras --no-dev --no-editable -o requirements.txt

      - name: Sync uv
        run: uv pip install --no-installer-metadata --no-compile-bytecode --python-platform x86_64-manylinux2014 --python 3.12 --target lambda_package -r requirements.txt

      - name: Sync uv
        run: zip -rq lambda_package.zip lambda_package

      - name: Upload lambda_package.zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG_NAME="${GITHUB_REF##*/}"
          gh release upload "$TAG_NAME" lambda_package.zip --clobber --repo "$GITHUB_REPOSITORY"
