name: Publish lambda

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          enable-uv-cache: false # No caching to ensure correct dependencies for publishing
          sync-uv: false

      # Sadly there appears to be no more elegant way to exclude certain packages when exporting requirements with uv/pip
      - name: Define requirements for lambda package
        run: |
          echo "typer" > no-requirements.txt
          uv export \
            --frozen \
            --all-extras \
            --no-emit-package click \
            --no-emit-package colorama \
            --no-emit-package markdown-it-py \
            --no-emit-package mdurl \
            --no-emit-package pygments \
            --no-emit-package rich \
            --no-emit-package shellingham \
            --no-emit-package typer \
            --no-dev \
            --no-editable \
            -o requirements.txt

      - name: Pip install dependencies for lambda
        run: |
          uv pip install \
            --excludes no-requirements.txt \
            --no-installer-metadata \
            --no-compile-bytecode \
            --python-platform x86_64-manylinux2014 \
            --python 3.12 \
            --target lambda_package \
            --requirements requirements.txt

      - name: Package lambda code
        run: |
          cd lambda_package
          zip -rq ../lambda_package.zip .

      - name: Upload lambda_package.zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG_NAME="${GITHUB_REF##*/}"
          gh release upload "$TAG_NAME" lambda_package.zip --clobber --repo "$GITHUB_REPOSITORY"
